### ISSUE TITLE
Error when running roslaunch

### ISSUE THREAD

**Issue by hxlee309** [Mayankm96/airsim_ros_client#1]
Hi,

When I run "roslaunch airsim_ros_client publish_tf.launch", I encountered the following error: 
"
Invalid <arg> tag: airsim_ros_wrapper
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/mnt/e/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share.

Arg xml is <arg default="$(find airsim_ros_wrapper)/urdf/robot/dji_m100_airsim.urdf.xacro" name="model"/>
The traceback for the exception was written to the log file
"
Also, I am not able to find airsim_ros_wrapper; instead, I can only find airsism_ros_client.

Please suggest what might go wrong.

Thanks,

Ethan

**Comment by Mayankm96** [comment]
Oh sorry, I recently changed the package name and forgot to change it on the launch files. I shall fix this error now. Thank you for pointing it out.

**Comment by Mayankm96** [comment]
It should be fixed now.

**Comment by hxlee309** [comment]
Hi,

Thanks for the update. Actually when I run "roslaunch airsim_ros_client publish_tf.launch" after I open the AirSim simulator, I am still getting the error below 

"
Invalid <arg> tag: airsim_ros_wrapper
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/mnt/e/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share.

Arg xml is <arg default="$(find airsim_ros_wrapper)/urdf/robot/dji_m100_airsim.urdf.xacro" name="model"/>
The traceback for the exception was written to the log file
"

Please suggest what might go wrong.

Thanks,

Ethan

**Comment by Mayankm96** [comment]
Could you please run it again and check? I made some more fixes with the package names in the launch files. The issue was earlier I named this package as `airsim_ros_wrapper` and now, I have changed it to `airsim_ros_client`. That is why you are getting the error. 

Let me know if the issue still persists.

**Comment by hxlee309** [comment]
Thanks, it works now! I can read the following topics after I type $ rostopic list
![image](https://user-images.githubusercontent.com/33882690/47225357-e2930180-d38b-11e8-8c77-67b6c9ee8524.png)
